### ISSUE TITLE
Possible error in gradient computation

### ISSUE THREAD

**Issue by hercky** [dchetelat/acer#1]
In the line for calculating the kl constrain: https://github.com/dchetelat/acer/blob/fbfaba1b0c7b627d19da58ee37aac75ad6ef6478/agent.py#L356, the denominator has the square of the actual gradient, whereas in the algorithm in the original paper it is the norm of the kl_gradient. Is it something intentional by design?

**Comment by dchetelat** [comment]
Good point, that was probably a mistake. I changed it to match the paper - it didn't seem to change anything.

Thanks for pointing it out!
